"""
Zorva backend — FastAPI entry point.

Run locally with:
    uvicorn app.main:app --reload

Then visit http://127.0.0.1:8000/docs for interactive API docs
(auto-generated by FastAPI from the route/model definitions).
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.routes import matches, users, ratings, subscriptions, insights

app = FastAPI(title="Zorva API", version="0.1.0")

# Allow mobile & web clients to call this API.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(matches.router)
app.include_router(users.router)
app.include_router(ratings.router)
app.include_router(subscriptions.router)
app.include_router(insights.router)



@app.get("/health")
def health_check():
    return {"status": "ok"}